name: CI

on:
  push: # quando um push for para a branch main
    branches:
      - "main"
  pull_request: # quando um pull request for se integrar a branch main
    branches:
      - "main"

  workflow_dispatch:

jobs:
  lint: # verificar estilo
    strategy: # cuidado com indentação
      fail-fast: true # se true, caso dê erro em alguma coisa tudo para
      matrix:
        python-version: ['3.10'] # qual versão do python será testada no github
        os: [ubuntu-latest] # qual sistema operacional
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]' # testa instalacao
      - name: Look for style errors
        run: pflake8
      - name: Check importing style
        run: isort dundie tests integration setup.py
      - name: Look for auto-format errors
        run: black --check --diff dundie tests integration # roda o black
      # e mostra onde o código está mal formatado

  tests:
    needs: lint # esse bloco precisa que o bloco lint tenha dado certo
    strategy: # cuidado com indentação
      fail-fast: false #se true, caso dê erro em alguma coisa tudo para
      matrix:
        python-version: ['3.9', '3.10'] # qual versão do python será testada no github
        os: [ubuntu-latest] # qual sistema operacional
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]' # testa instalacao
      - name: Run tests
        #run: pytest -vv tests integration # roda os testes unitários e de integracao
        run: pytest -v --junitxml=test-result.xml # gera o report JUNIT
      - name: Publish junit results # publica o resultado (pode ser publicado em várias plataformas)
        uses: EnricoMi/publish-unit-test-result-action@v1 # usa uma action opensource criada pelo usuario Enrico
        if: always() # se não tiver isso, será feito só quando falhas
        with:
          files: test-result.xml
          check_name: resultado_teste (Python ${{matrix.python-version}})
